describe('Library', () => {
    beforeEach(() => {
        cy.visit('https://www.empik.com/')
    })

    it('log in and check library', () => {
        cy.get('.empikNav__user > .empikNav__userLink.userMenu')
            .click()
        cy.get('input#user-email')
            .type('xitofe3408@chatich.com')
            .should('have.value', 'xitofe3408@chatich.com')
        cy.get('.show .e-btn--primary')
            .click()
        cy.get('input#user-password')
            .type('Pzt9r!KuUSq!tBE!fSWAH$MT%')
            .should('have.value', 'Pzt9r!KuUSq!tBE!fSWAH$MT%')
        cy.get('.show .e-btn--primary')
            .click()
        cy.get('.empikNav__user > .empikNav__userLink.userMenu')
            .click()
        cy.url().should('include', '/twoje-konto')
        cy.get('a[title=\'Moja biblioteka\']')
            .click()
        cy.url().should('include', '/twoje-konto/schowek/moja-biblioteczka')
        cy.get('.showAllLink')
            .click()
        cy.url().should('include', '/twoje-konto/produkty-cyfrowe/mp3')
        cy.get('.menuNav [href=\'\\/twoje-konto\\/produkty-cyfrowe\\/ebooki\']')
            .click()
        cy.url().should('include', '/twoje-konto/produkty-cyfrowe/ebooki')
        cy.get('[href=\'\\/twoje-konto\\/produkty-cyfrowe\\/audiobooki\']')
            .click()
        cy.url().should('include', '/twoje-konto/produkty-cyfrowe/audiobooki')
        cy.get('[href=\'\\/twoje-konto\\/produkty-cyfrowe\\/gry\']')
            .click()
        cy.url().should('include', '/twoje-konto/produkty-cyfrowe/gry')
        cy.get('[href=\'\\/twoje-konto\\/produkty-cyfrowe\\/mp3\']')
            .click()
        cy.url().should('include', '/twoje-konto/produkty-cyfrowe/mp3')
        cy.get('[href=\'\\/twoje-konto\\/produkty-cyfrowe\\/bilety\']')
            .click()
        cy.url().should('include', '/twoje-konto/produkty-cyfrowe/bilety')
    })
})