describe('Order history', () => {
    beforeEach(() => {
        cy.visit('https://www.empik.com/')
    })

    it('log in and check order history', () => {
        cy.get('.empikNav__user > .empikNav__userLink.userMenu')
            .click()
        cy.get('input#user-email')
            .type('xitofe3408@chatich.com')
            .should('have.value', 'xitofe3408@chatich.com')
        cy.get('.show .e-btn--primary')
            .click()
        cy.get('input#user-password')
            .type('Pzt9r!KuUSq!tBE!fSWAH$MT%')
            .should('have.value', 'Pzt9r!KuUSq!tBE!fSWAH$MT%')
        cy.get('.show .e-btn--primary')
            .click()
        cy.get('.empikNav__user > .empikNav__userLink.userMenu')
            .click()
        cy.url().should('include', '/twoje-konto')
        cy.get('a[title=\'Zamówienia Empik.com\']')
            .click()
        cy.url().should('include', '/twoje-konto/zamowienia')
        cy.get('span[title=\'Z SALONÓW EMPIK\']')
            .click()
        cy.url().should('include', '/twoje-konto/zamowienia-offline')
        cy.get('span[title=\'EMPIK GO\']')
            .click()
        cy.url().should('include', '/twoje-konto/abonamenty')
        cy.get('span[title=\'EMPIK PREMIUM\']')
            .click()
        cy.url().should('include', '/twoje-konto/premium')
        cy.get('span[title=\'EMPIK MUSIC\']')
            .click()
        cy.url().should('include', '/twoje-konto/music')
    })
})